/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ConexaoBD;
import appRevista.Artigo;
import appRevista.Edicao;
import Controle.EscrevaArquivos;
import Controle.EscreverBinario;
import appRevista.Revista;
import Controle.arrayBD;
import Controle.revistaExisteException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;

/**
 *
 * @author erik_
 */
public class janelaArtigo extends javax.swing.JFrame {
    
    private final ConexaoBD conexao = new ConexaoBD();
    private final arrayBD arrayBD = new arrayBD(conexao.carregaBanco());

    /**
     * Creates new form janelaArtigo
     */
    public janelaArtigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonNovaEdicao = new javax.swing.JToggleButton();
        txt_ID = new javax.swing.JTextField();
        consultaEdicao = new javax.swing.JToggleButton();
        limpaCampo = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtEscritor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRevista = new javax.swing.JTextField();
        buttonSalvarBim = new javax.swing.JToggleButton();
        jButtonExcluir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Artigos");

        jLabel1.setText("Escritor:");

        jLabel4.setText("ID:");

        buttonNovaEdicao.setText("Cadastrar");
        buttonNovaEdicao.setAutoscrolls(true);
        buttonNovaEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonNovaEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovaEdicaoActionPerformed(evt);
            }
        });

        consultaEdicao.setText("Consultar");
        consultaEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEdicaoActionPerformed(evt);
            }
        });

        limpaCampo.setText("Cancelar");
        limpaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaCampoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Edição:");

        jButton1.setText("Salvar em TXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        txtEscritor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscritorActionPerformed(evt);
            }
        });

        jLabel3.setText("Revista");

        buttonSalvarBim.setText("Salvar em Binario");
        buttonSalvarBim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarBimActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonNovaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(limpaCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSalvarBim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtRevista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                        .addComponent(txtEdicao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEscritor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ID, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonNovaEdicao)
                            .addComponent(limpaCampo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultaEdicao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSalvarBim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNovaEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovaEdicaoActionPerformed
        // TODO add your handling code here:
        buttonNovaEdicao.setSelected(false);
        cadastrarArray();
        
    }//GEN-LAST:event_buttonNovaEdicaoActionPerformed

    private void consultaEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEdicaoActionPerformed
        consultaEdicao.setSelected(false);
        javax.swing.JFrame consulta;
        consulta = new janelaConsultaArtigo();
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
    }//GEN-LAST:event_consultaEdicaoActionPerformed

    private void limpaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaCampoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_limpaCampoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        jButton1.setSelected(false);
        EscrevaArquivos escrever = new EscrevaArquivos();
        try {
            escrever.escreverTXT(new File(JOptionPane.showInputDialog("Caminho do arquivo")), true);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void txtEscritorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscritorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscritorActionPerformed

    private void buttonSalvarBimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarBimActionPerformed
        // TODO add your handling code here:
        buttonSalvarBim.setSelected(false);
        EscreverBinario escrever = new EscreverBinario();
        try {
            escrever.escreveBinario(new File(JOptionPane.showInputDialog("Caminho do arquivo")), true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonSalvarBimActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        jButtonExcluir.setSelected(false);  
        excluirArtigo();
    }//GEN-LAST:event_jButtonExcluirActionPerformed
    public final void cadastrarArray() {        
        Edicao edicao = new Edicao();
        Artigo artigo = new Artigo();
        Revista res = new Revista();
        cadastrarBanco(edicao, artigo, res);
        if (artigo.getID() == 0) {
        } else {
            if (arrayBD.insereArtigo(edicao, artigo, res)) {
                JOptionPane.showMessageDialog(null, "Cadastro bem sucedido!");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no cadastro tente novamente!");
            }
            txtEscritor.setText(null);
            txt_ID.setText(null);
            txtEdicao.setText(null);
        }
        txt_ID.requestFocus();
    }
    
    public final void cadastrarBanco(Edicao edicao, Artigo artigo, Revista res) {
        try {
            artigo.setID(Integer.parseInt(txt_ID.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, txt_ID.getText() + "\nNão e uma entrada valida.");
            txt_ID.setText(null);
        }
        artigo.setEscritor(txtEscritor.getText());
        try {
            edicao.setID(Integer.parseInt(txtEdicao.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, txt_ID.getText() + "\nNão e uma entrada valida.");
            JOptionPane.showMessageDialog(null, "Entre com o ID de uma edição ja cadastrada.");
            txt_ID.setText(null);
        }
        res.setNome(txtRevista.getText());
        
        if (artigo.getID() == 0) {
        } else {
            conexao.insereArtigo(res, edicao, artigo);
        }
    }
    
    public final void excluirArtigo(){
        Revista aux = new Revista();
        try{
        
        aux.setID(Integer.parseInt(JOptionPane.showInputDialog(null, "Entre com o ID do Escritor")));
        aux.setNome(JOptionPane.showInputDialog(null, "Entre com o NOME do Escritor"));
        if(aux.getID()!=0)
            if(conexao.excluiArtigo(aux).equalsIgnoreCase("Result set representing update count of 1"))
                JOptionPane.showMessageDialog(null,"Excluido com sucesso");
            else{
                JOptionPane.showMessageDialog(null,"Registro não encontrado");
                throw new revistaExisteException();
            }
         if(0==JOptionPane.showConfirmDialog(null,"Confirmar alteração no banco?")){
                 conexao.salvaNoBanco();
                 System.out.println("Deu certo!!");
        }
        }catch(NumberFormatException erro){
            JOptionPane.showMessageDialog(null,"Entrada invalida: \n"+erro.getMessage());
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao excluir: \n"+ex.getMessage());
        } catch(revistaExisteException ex){
            ex.artigoNaoExiste();
        } catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null,"Registro não encontrado: \n"+ex.getMessage());
        }
        conexao.atualizaArray();
        conexao.atualizacao();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaArtigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonNovaEdicao;
    private javax.swing.JToggleButton buttonSalvarBim;
    private javax.swing.JToggleButton consultaEdicao;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton limpaCampo;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEscritor;
    private javax.swing.JTextField txtRevista;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

}
