/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ConexaoBD;
import appRevista.Edicao;
import Controle.EscrevaArquivos;
import Controle.EscreverBinario;
import appRevista.Revista;
import Controle.arrayBD;
import Controle.revistaExisteException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erik_
 */
public class jfEdicao extends javax.swing.JFrame {

    private final ConexaoBD conexao = new ConexaoBD();
    private final arrayBD arrayBD = new arrayBD(conexao.carregaBanco());

    /**
     * Creates new form jfEdicao
     */
    public jfEdicao() {
        initComponents();
    }
    //private jfRevista arrayRevista = new jfRevista();
    //private ArrayList <Revista> array = arrayRevista.getArrayRevista();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLimpaCampo = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNUmero = new javax.swing.JTextField();
        txtRevista = new javax.swing.JTextField();
        jButtonNovaEdicao = new javax.swing.JToggleButton();
        jButtonConsultaEdicao = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txtEdicao = new javax.swing.JTextField();
        jButtonSalvarTXT = new javax.swing.JButton();
        jButtonSalvarBim = new javax.swing.JToggleButton();
        jButtonExcluir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Edições");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonLimpaCampo.setText("Cancelar");
        jButtonLimpaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaCampoActionPerformed(evt);
            }
        });

        jLabel1.setText("Lancamento:");

        jLabel2.setText("Numero da Edicao:");

        jLabel3.setText("Revista:");

        txtNUmero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNUmeroActionPerformed(evt);
            }
        });

        txtRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRevistaActionPerformed(evt);
            }
        });

        jButtonNovaEdicao.setText("Cadastrar");
        jButtonNovaEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaEdicaoActionPerformed(evt);
            }
        });

        jButtonConsultaEdicao.setText("Consultar");
        jButtonConsultaEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaEdicaoActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        txtEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicaoActionPerformed(evt);
            }
        });

        jButtonSalvarTXT.setText("Salvar em TXT");
        jButtonSalvarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jButtonSalvarBim.setText("Salvar em Binario");
        jButtonSalvarBim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarBimActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(txtEdicao))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNUmero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNovaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonConsultaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLimpaCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSalvarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvarBim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNUmero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarTXT)
                    .addComponent(jButtonLimpaCampo)
                    .addComponent(jButtonNovaEdicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarBim)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonConsultaEdicao)
                        .addComponent(jButtonExcluir)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovaEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaEdicaoActionPerformed
        // TODO add your handling code here:
        jButtonNovaEdicao.setSelected(false);
        cadastraArray();
    }//GEN-LAST:event_jButtonNovaEdicaoActionPerformed

    private void txtRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRevistaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRevistaActionPerformed

    private void jButtonLimpaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaCampoActionPerformed
        // TODO add your handling code here:
        jButtonLimpaCampo.setSelected(false);
        dispose();
    }//GEN-LAST:event_jButtonLimpaCampoActionPerformed

    private void jButtonConsultaEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaEdicaoActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Recurso ainda nâo disponevel!");
        jButtonConsultaEdicao.setSelected(false);
        javax.swing.JFrame consulta;

        consulta = new janelaConsultaEdicao();
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
        consulta.setVisible(true);
        consulta.setResizable(false);
    }//GEN-LAST:event_jButtonConsultaEdicaoActionPerformed

    private void txtEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicaoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        jButtonSalvarTXT.setSelected(false);
        EscrevaArquivos escrever = new EscrevaArquivos();
        try {
            escrever.escreverTXT(new File(JOptionPane.showInputDialog("Caminho do arquivo")), true);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void txtNUmeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNUmeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNUmeroActionPerformed

    private void jButtonSalvarBimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarBimActionPerformed
        // TODO add your handling code here:
        jButtonSalvarBim.setSelected(false);
        EscreverBinario escrever = new EscreverBinario();
        try {
            escrever.escreveBinario(new File(JOptionPane.showInputDialog("Caminho do arquivo")), true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarBimActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        jButtonExcluir.setSelected(false);
                excluirEdicao();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    public final void cadastraArray() {
        Revista revista = new Revista();
        Edicao edicao = new Edicao();
        cadastraBanco(revista, edicao);
        if (edicao.getID() == 0 || edicao.getNumEdicao() == 00) {
        } else {
            if (arrayBD.insereEdicao(edicao, revista)) {
                JOptionPane.showMessageDialog(null, "Cadastro bem sucedido!");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no cadastro tente novamente!");
            }
            txtEdicao.setText(null);
            txtRevista.setText(null);
            txt_ID.setText(null);
            txtNUmero.setText(null);
        }
        txt_ID.requestFocus();
    }

    public final void cadastraBanco(Revista revista, Edicao edicao) {
        try {
            edicao.setID(Integer.parseInt(txt_ID.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, txt_ID.getText() + "\nNão e uma entrada valida.");
            txt_ID.setText(null);
        }
        edicao.setEdicao(txtEdicao.getText());
        try {
            edicao.setNumEdicao(Integer.parseInt(txtNUmero.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, txt_ID.getText() + "\nNão e uma entrada valida.");
            txtNUmero.setText(null);
        }
        revista.setNome(txtRevista.getText());

        if (edicao.getID() == 0 || edicao.getNumEdicao() == 00) {
        } else {
            conexao.insereEdicao(revista, edicao);
        }
    }

    public final void excluirEdicao(){
        Revista aux = new Revista();
        try{
        
        aux.setID(Integer.parseInt(JOptionPane.showInputDialog(null, "Entre com o ID da Edição")));
        aux.setNome(JOptionPane.showInputDialog(null, "Entre com o mes da Edicao"));
        if(aux.getID()!=0)
            if(conexao.excluiEdicao(aux).equalsIgnoreCase("Result set representing update count of 1"))
                JOptionPane.showMessageDialog(null,"Excluido com sucesso");
            else{
                JOptionPane.showMessageDialog(null,"Registro não encontrado");
                throw new revistaExisteException();
            }
         if(0==JOptionPane.showConfirmDialog(null,"Confirmar alteração no banco?")){
                 conexao.salvaNoBanco();
                 System.out.println("Deu certo!!");
        }
        }catch(NumberFormatException erro){
            JOptionPane.showMessageDialog(null,"Entrada invalida: \n"+erro.getMessage());
        } catch (SQLException ex){
            if(ex.getErrorCode() == 1451){
                JOptionPane.showMessageDialog(null,"Erro ao excluir:\nO registro esta sendo utilizado por um ou mais Artigos");
            } else {
                JOptionPane.showMessageDialog(null,"Erro ao excluir: \n"+ex.getMessage());
            }
        } catch(revistaExisteException ex){
            ex.edicaoNaoExiste();
        } catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null,"Registro não encontrado: \n"+ex.getMessage());
        }
        conexao.atualizaArray();
        conexao.atualizacao();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfEdicao().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonConsultaEdicao;
    private javax.swing.JToggleButton jButtonExcluir;
    private javax.swing.JToggleButton jButtonLimpaCampo;
    private javax.swing.JToggleButton jButtonNovaEdicao;
    private javax.swing.JToggleButton jButtonSalvarBim;
    private javax.swing.JButton jButtonSalvarTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtNUmero;
    private javax.swing.JTextField txtRevista;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables
}
