/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ConexaoBD;
import Controle.EscrevaArquivos;
import Controle.EscreverBinario;
import appRevista.Revista;
import Controle.arrayBD;
import Controle.revistaExisteException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erik_
 */
public class jfRevista extends javax.swing.JFrame {

    private janelaConsultaRevista consulta = new janelaConsultaRevista();
    private ConexaoBD conexao = new ConexaoBD();
    private final arrayBD arrayBD = new arrayBD(conexao.carregaBanco());

    /**
     * Creates new form jfRevista
     */
    public jfRevista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonnovaRevista = new javax.swing.JToggleButton();
        jByuttonConsultarRevista = new javax.swing.JToggleButton();
        limpaCampos = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoNome = new javax.swing.JTextField();
        textoEditora = new javax.swing.JTextField();
        textoSite = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jButtonSalvarTXT = new javax.swing.JButton();
        jbuttonSalvarBim = new javax.swing.JToggleButton();
        jButtonExcluir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Revista");

        jButtonnovaRevista.setText("Cadastrar");
        jButtonnovaRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnovaRevistaActionPerformed(evt);
            }
        });

        jByuttonConsultarRevista.setText("Consultar");
        jByuttonConsultarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jByuttonConsultarRevistaActionPerformed(evt);
            }
        });

        limpaCampos.setText("Cancelar");
        limpaCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaCamposActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Editora:");

        jLabel3.setText("Site:");

        textoSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSiteActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        jButtonSalvarTXT.setText("Salvar em TXT");
        jButtonSalvarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jbuttonSalvarBim.setText("Salvar em Binario");
        jbuttonSalvarBim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSalvarBimActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoSite)
                            .addComponent(textoEditora)
                            .addComponent(textoNome)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonnovaRevista)
                            .addComponent(jByuttonConsultarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(limpaCampos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuttonSalvarBim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonnovaRevista)
                            .addComponent(jButtonExcluir)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvarTXT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonSalvarBim)
                    .addComponent(jByuttonConsultarRevista)
                    .addComponent(limpaCampos))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSiteActionPerformed

    private void jButtonnovaRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnovaRevistaActionPerformed
        // TODO add your handling code here:
        jButtonnovaRevista.setSelected(false);
        cadastraArray();
    }//GEN-LAST:event_jButtonnovaRevistaActionPerformed

    private void jByuttonConsultarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jByuttonConsultarRevistaActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Recurso ainda nâo disponevel!");
        jByuttonConsultarRevista.setSelected(false);
        if (consulta == null) {
            consulta = new janelaConsultaRevista();
            consulta.setLocationRelativeTo(null);
            consulta.setVisible(true);
            consulta.setResizable(false);
        } else {
            consulta.setLocationRelativeTo(null);
            consulta.setVisible(true);
            consulta.setResizable(false);
        }
    }//GEN-LAST:event_jByuttonConsultarRevistaActionPerformed

    private void limpaCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaCamposActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_limpaCamposActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        jButtonSalvarTXT.setSelected(false);
        EscrevaArquivos escrever = new EscrevaArquivos();
        try {
            escrever.escreverTXT(new File(JOptionPane.showInputDialog("Caminho do arquivo")), true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void jbuttonSalvarBimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSalvarBimActionPerformed
        // TODO add your handling code here:
        jbuttonSalvarBim.setSelected(false);
        EscreverBinario escrever = new EscreverBinario();
        try {
            escrever.escreveBinario(new File(JOptionPane.showInputDialog("Caminho do arquivo")), true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo " + ex.getMessage());
        }
    }//GEN-LAST:event_jbuttonSalvarBimActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        jButtonExcluir.setSelected(false);
        excluirRevista();
    }//GEN-LAST:event_jButtonExcluirActionPerformed
    public final void cadastraArray() {
        Revista revista = new Revista();
        cadastraBanco(revista);
        if (revista.getID() == 0) {
        } else {
            if (arrayBD.insereRevista(revista)) {
                JOptionPane.showMessageDialog(null, "Cadastro bem sucedido!");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no cadastro tente novamente!");
            }
            txt_ID.setText(null);
            textoEditora.setText(null);
            textoNome.setText(null);
            textoSite.setText(null);
        }
        txt_ID.requestFocus();
    }

    public final void cadastraBanco(Revista revista) {
        try {
            revista.setID(Integer.parseInt(txt_ID.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, txt_ID.getText() + "\nNão e uma entrada valida.");
            txt_ID.setText(null);
        }
        revista.setNome(textoNome.getText());
        revista.setSite(textoSite.getText());
        revista.setEditora(textoEditora.getText());

        if (revista.getID() == 0) {
        } else {
            conexao.insereRevista(revista);
        }

    }

    public final void excluirRevista() {
            
        Revista aux = new Revista();
        try {
            aux.setID(Integer.parseInt(JOptionPane.showInputDialog(null, "Entre com o ID da Revista")));
            aux.setNome(JOptionPane.showInputDialog(null, "Entre com o nome da Revista"));
            if (aux.getID() != 0) {
                if (conexao.excluiRevista(aux).equalsIgnoreCase("Result set representing update count of 1")) {
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Registro não encontrado");
                    throw new revistaExisteException();
                }
            }
            if (0 == JOptionPane.showConfirmDialog(null, "Confirmar alteração no banco?")) {
                conexao.salvaNoBanco();
                System.out.println("Deu certo!!");
            }
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Entrada invalida: \n" + erro.getMessage());
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 1451) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir:\nO registro esta sendo utilizado por uma ou mais Edições");
            }  else{
            JOptionPane.showMessageDialog(null, "Erro ao excluir: \n" + ex.getMessage());
            }
        } catch (revistaExisteException ex) {
            ex.revistaNaoExiste();
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Registro não encontrado: \n" + ex.getMessage());
        }
        conexao.atualizaArray();
        arrayBD.atualizaArray();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaArtigo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvarTXT;
    private javax.swing.JToggleButton jButtonnovaRevista;
    private javax.swing.JToggleButton jByuttonConsultarRevista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jbuttonSalvarBim;
    private javax.swing.JToggleButton limpaCampos;
    private javax.swing.JTextField textoEditora;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoSite;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables
}
