/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ConexaoBD;
import Controle.LerBinario;
import Controle.ReadFiles;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erik_
 */
public class telaMenu extends javax.swing.JFrame {

    /**
     * Creates new form telaMenu
     */
    public telaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
    }

    private jfEdicao edicao = new jfEdicao();
    private jfRevista revista = new jfRevista();
    private janelaArtigo artigo = new janelaArtigo();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvarNoBanco = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        munuCadRevista = new javax.swing.JMenuItem();
        menuConsultarRevista = new javax.swing.JMenuItem();
        jMenuItemExcluirRevista = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadEdicao = new javax.swing.JMenuItem();
        menuConsultarEdicao = new javax.swing.JMenuItem();
        jMenuItemExcluir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Revistas");

        jButtonSalvarNoBanco.setText("Salvar No Banco");
        jButtonSalvarNoBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarNoBancoActionPerformed(evt);
            }
        });

        jMenu1.setText("Revista");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        munuCadRevista.setText("Cadastrar");
        munuCadRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munuCadRevistaActionPerformed(evt);
            }
        });
        jMenu1.add(munuCadRevista);

        menuConsultarRevista.setText("Consultar");
        menuConsultarRevista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConsultarRevistaMouseClicked(evt);
            }
        });
        menuConsultarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarRevistaActionPerformed(evt);
            }
        });
        jMenu1.add(menuConsultarRevista);

        jMenuItemExcluirRevista.setText("Excluir Revista");
        jMenuItemExcluirRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirRevistaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExcluirRevista);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicao");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuCadEdicao.setText("Cadastrar");
        menuCadEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadEdicaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadEdicao);

        menuConsultarEdicao.setText("Consultar");
        menuConsultarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarEdicaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultarEdicao);

        jMenuItemExcluir.setText("Excluir Edição");
        jMenuItemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemExcluir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Artigo");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Consultar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Excluir Registro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        jMenu4.setText("Carregar TXT");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarregarTXT(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Carregar Binario");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarregarBinario(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addComponent(jButtonSalvarNoBanco)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jButtonSalvarNoBanco)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void munuCadRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munuCadRevistaActionPerformed
        if (revista == null) {
            revista = new jfRevista();
            revista.setLocationRelativeTo(null);
            revista.setVisible(true);
            revista.setResizable(false);
        } else {
            revista.setLocationRelativeTo(null);
            revista.setVisible(true);
            revista.setResizable(false);
        }
    }//GEN-LAST:event_munuCadRevistaActionPerformed

    private void menuConsultarRevistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConsultarRevistaMouseClicked
        // TODO add your handling code here:
        if (revista == null) {
            revista = new jfRevista();
            revista.setLocationRelativeTo(null);
            revista.setVisible(true);
            revista.setResizable(false);
        } else {
            revista.setLocationRelativeTo(null);
            revista.setVisible(true);
            revista.setResizable(false);
        }

    }//GEN-LAST:event_menuConsultarRevistaMouseClicked

    private void menuCadEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadEdicaoActionPerformed
        if (edicao == null) {
            edicao = new jfEdicao();
            edicao.setLocationRelativeTo(null);
            edicao.setVisible(true);
            edicao.setResizable(false);
        } else {
            edicao.setLocationRelativeTo(null);
            edicao.setVisible(true);
            edicao.setResizable(false);
        }

    }//GEN-LAST:event_menuCadEdicaoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuConsultarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarEdicaoActionPerformed
        // TODO add your handling code here:
             /*if(edicao == null){
         edicao = new jfEdicao();
         edicao.setLocationRelativeTo(null);
         edicao.setVisible(true);
         edicao.setResizable(false);
         }else{
         edicao.setLocationRelativeTo(null);
         edicao.setVisible(true);
         edicao.setResizable(false);
         }
         */
        //JOptionPane.showMessageDialog(null,"Recurso ainda nâo disponevel!");

        javax.swing.JFrame consulta;

        consulta = new janelaConsultaEdicao();
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);
        consulta.setVisible(true);
        consulta.setResizable(false);

    }//GEN-LAST:event_menuConsultarEdicaoActionPerformed

    private void menuConsultarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarRevistaActionPerformed
        /* if(revista == null){
         revista = new jfRevista();
         revista.setLocationRelativeTo(null);
         revista.setVisible(true);
         revista.setResizable(false);
         }else{
         revista.setLocationRelativeTo(null);
         revista.setVisible(true);
         revista.setResizable(false);
         }*/
        //JOptionPane.showMessageDialog(null,"Recurso ainda nâo disponevel!");
        javax.swing.JFrame consulta;
        consulta = new janelaConsultaRevista();
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);

    }//GEN-LAST:event_menuConsultarRevistaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        /*if(artigo == null){
         artigo = new janelaArtigo();
         artigo.setLocationRelativeTo(null);
         artigo.setVisible(true);
         artigo.setResizable(false);
         }else{
         artigo.setLocationRelativeTo(null);
         artigo.setVisible(true);
         artigo.setResizable(false);
         }*/
        //JOptionPane.showMessageDialog(null,"Recurso ainda nâo disponevel!");
        javax.swing.JFrame consulta;
        consulta = new janelaConsultaArtigo();
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        consulta.setResizable(false);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (artigo == null) {
            artigo = new janelaArtigo();
            artigo.setLocationRelativeTo(null);
            artigo.setVisible(true);
            artigo.setResizable(false);
        } else {
            artigo.setLocationRelativeTo(null);
            artigo.setVisible(true);
            artigo.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:

        ReadFiles readFiles = new ReadFiles();
        try {
            readFiles.read(new File(JOptionPane.showInputDialog("Digite o endereco do arquivo com o nome do arquivo")));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel carregar o arquivo");
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuCarregarTXT(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarregarTXT
        // TODO add your handling code here:

        ReadFiles readFiles = new ReadFiles();
        try {
            readFiles.read(new File(JOptionPane.showInputDialog("Digite o endereco do arquivo com o nome do arquivo")));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel carregar o arquivo");
        } catch (Exception ex) {
            System.out.println("Erro na leitura do objeto. " + ex);
        }
    }//GEN-LAST:event_jMenuCarregarTXT

    private void jMenuCarregarBinario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarregarBinario
        // TODO add your handling code here:
        LerBinario leitor = new LerBinario();
        try {
            leitor.leitorBinario(new File(JOptionPane.showInputDialog("Caminho do arquivo")));
        } catch (ClassNotFoundException erro) {
            System.out.println("Classe nao encontrada. " + erro);
        } catch (java.io.EOFException erro) {
            System.out.println("Final de arquivo. " + erro);
        } catch (IOException erro) {
            System.out.println("Erro na leitura do objeto. " + erro);
        } catch (Exception ex) {
            System.out.println("Erro na leitura do objeto. " + ex);
        }
    }//GEN-LAST:event_jMenuCarregarBinario

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        LerBinario leitor = new LerBinario();
        try {
            leitor.leitorBinario(new File(JOptionPane.showInputDialog("Caminho do arquivo")));
        } catch (ClassNotFoundException erro) {
            System.out.println("Classe nao encontrada. " + erro);
        } catch (java.io.EOFException erro) {
            System.out.println("Final de arquivo. " + erro);
        } catch (IOException erro) {
            System.out.println("Erro na leitura do objeto. " + erro);
        } catch (Exception ex) {
            System.out.println("Erro na leitura do objeto. " + ex);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jButtonSalvarNoBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarNoBancoActionPerformed
        jButtonSalvarNoBanco.requestFocus();
        new ConexaoBD().salvaNoBanco();
    }//GEN-LAST:event_jButtonSalvarNoBancoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       artigo.excluirArtigo();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirActionPerformed
        // TODO add your handling code here:
        edicao.excluirEdicao();
    }//GEN-LAST:event_jMenuItemExcluirActionPerformed

    private void jMenuItemExcluirRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirRevistaActionPerformed
        // TODO add your handling code here:
        revista.excluirRevista();
    }//GEN-LAST:event_jMenuItemExcluirRevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new telaMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvarNoBanco;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemExcluir;
    private javax.swing.JMenuItem jMenuItemExcluirRevista;
    private javax.swing.JMenuItem menuCadEdicao;
    private javax.swing.JMenuItem menuConsultarEdicao;
    private javax.swing.JMenuItem menuConsultarRevista;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem munuCadRevista;
    // End of variables declaration//GEN-END:variables
}
